steps:
  # get environment variables from secret manager
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: [ '-c', 'gcloud secrets versions access latest --secret=env > /workspace/.env' ]
  # build docker image
  - name: gcr.io/cloud-builders/docker
    args: [
      'build',
      '-t', 'gcr.io/${PROJECT_ID}/jam-demo:${BRANCH_NAME}_${SHORT_SHA}',
      '-f', 'Dockerfile',
      '.']
  # tag new version to latest
  - name: gcr.io/cloud-builders/docker
    args: [
      'tag', 'gcr.io/${PROJECT_ID}/jam-demo:${BRANCH_NAME}_${SHORT_SHA}',
      'gcr.io/${PROJECT_ID}/jam-demo:latest',
    ]
  # push to google container registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      "push", "gcr.io/${PROJECT_ID}/jam-demo"
      ]
  # deploy container to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: [
      '-c',
      'cloudbuildenv=`cat /workspace/.env` && gcloud run deploy jam-demo --image gcr.io/${PROJECT_ID}/jam-demo:${BRANCH_NAME}_${SHORT_SHA} --region asia-east1 --platform managed --update-env-vars $cloudbuildenv'
      ]
timeout: 1234s
